
CREATE TABLE `sut` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `code` varchar(20) DEFAULT NULL,
 `name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;


