DROP DATABASE `paftp`;
create SCHEMA `paftp` DEFAULT CHARACTER SET utf8;
USE `paftp`;
source C:\GitHub\paftp\PAFTestPlatform\sql\create_applysutstatus.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_version.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_userinfo_position.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_userinfo_department.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_userinfo.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_user.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_sut_group.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_sut.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_role.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_user_role.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_scene.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_strategetype.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_stressresult.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_tpsresult.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_testsuite.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_testcase.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_permission.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_role_permission.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_responsetimeresult.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_networkresult.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_memoryresult.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_errorlog.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_diskresult.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_cpuresult.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_casestep.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_casechangehistory.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_casechangeoperation.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_applysut.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_testpass.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_testsuite_result.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_testcase_result.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_testcase_result_content.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_analysecomment_history.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\create_analysecomment_content.sql
source C:\GitHub\paftp\PAFTestPlatform\sql\SystemInsertstatictables.sql